defaults:
  database: local
models:
- vendor: openai
  name: gpt4o
  model_ref: gpt-4o
  key_var: OPENAI_API_KEY
databases:
- name: local
  type: duckdb
  dataset: db/
authentication:
  google:
    client_id: 4786469222-dlvn0v70lh8e5fffielgncmjnfq73uk3.apps.googleusercontent.com
    client_secret_var: GOOGLE_CLIENT_SECRET
